// @ts-check
import js from '@eslint/js';
import eslintConfigPrettier from 'eslint-config-prettier';

/**
 * Directories/files no config in this monorepo should ever lint.
 */
export const ignores = [
  '**/dist/**',
  '**/build/**',
  '**/.next/**',
  '**/out/**',
  '**/coverage/**',
  '**/node_modules/**',
  '**/prisma/generated/**',
  '**/playwright-report/**',
  '**/test-results/**',
  '**/.vitest-cache/**',
  '**/*.tsbuildinfo',
  // Regenerated by `next dev`/`next build` on every run; its content
  // (triple-slash references and all) is dictated by Next.js, not by
  // our conventions.
  '**/next-env.d.ts',
  // External reference-only design mockups/support scripts, not
  // application source — untracked, never meant to be committed or
  // linted (see .gitignore).
  '**/Admin console build verification package/**',
];

/**
 * Repo-wide safety rules. These encode invariants from
 * PRODUCT/docs/12-repository-structure.md §19.8 and
 * PRODUCT/docs/16-execution-protocol.md §24.4 as enforceable lint errors
 * rather than conventions that rely on memory.
 *
 * Money invariant (INV-1, BR-1): all monetary arithmetic happens as
 * BigInt minor units inside @direct-order/money. `Math.round`, `.toFixed`,
 * and `parseFloat` are the three ways float arithmetic silently creeps
 * into a money path, so they are banned everywhere. If a future phase
 * needs float formatting for something that is genuinely NOT money
 * (a star rating, a distance in km), use an explicit
 * `// eslint-disable-next-line no-restricted-syntax -- not money: <reason>`.
 */
export const customRules = {
  rules: {
    'no-restricted-syntax': [
      'error',
      {
        selector: "CallExpression[callee.object.name='Math'][callee.property.name='round']",
        message:
          'Math.round is banned for money. Use packages/money (BigInt half-up rounding). If this is not money, add a justified eslint-disable comment.',
      },
      {
        selector: "CallExpression[callee.property.name='toFixed']",
        message:
          '.toFixed() is banned for money formatting. Use formatINR() from @direct-order/money. If this is not money, add a justified eslint-disable comment.',
      },
      {
        selector: "CallExpression[callee.name='parseFloat']",
        message:
          'parseFloat is banned for money parsing. Use toMinor() from @direct-order/money. If this is not money, add a justified eslint-disable comment.',
      },
      {
        selector:
          'CallExpression[callee.property.name=/^(queryRawUnsafe|executeRawUnsafe)$/] > TemplateLiteral[expressions.length>0]',
        message:
          'Raw SQL built from a template literal with interpolation is forbidden (SQL injection risk). Use $queryRaw with tagged-template parameters, or Prisma.sql.',
      },
      {
        selector:
          "CallExpression[callee.property.name=/^(queryRawUnsafe|executeRawUnsafe)$/] > BinaryExpression[operator='+']",
        message:
          'Raw SQL built from string concatenation is forbidden (SQL injection risk). Use $queryRaw with tagged-template parameters, or Prisma.sql.',
      },
      {
        selector: "JSXAttribute[name.name='dangerouslySetInnerHTML']",
        message:
          'dangerouslySetInnerHTML is banned. Restaurant/menu/review content is untrusted input (BR-120) and must never be rendered as raw HTML.',
      },
    ],
  },
};

/**
 * Base flat-config blocks shared by every package and app in the
 * monorepo. Consuming eslint.config.js files spread this array and
 * append their own language/environment-specific blocks (TypeScript
 * project references, React/Next rules, Node globals, etc).
 */
export const base = [{ ignores }, js.configs.recommended, customRules, eslintConfigPrettier];

export default base;
